# Python для Анализа Данных

# Лекция 4: Научные вычисления с NumPy

# 1. Ретроспектива домашних заданий

## 1. Функции

* Если мы хотим, чтобы функция что-то возвращала, то пишем **return**
* Если мы хотим, чтобы функция что-то печатала (выводила на экран), то пишем **print()**
* Не надо писать **return print (!!!)**

#### Так правильно

In [ ]:
# Если функция должна что-то выводить на экран, то:
def my_sum_1(a, b):
    c = a + b
    print(c)

In [ ]:
# Если функция должна что-то возвращать, то:
## Вариант 1
def my_sum_2(a, b):
    c = a + b
    return c

In [ ]:
# Если функция должна что-то возвращать, то:
## Вариант 2
def my_sum_3(a, b):
    return a + b

In [ ]:
# Результат работы функции 1
## Выводит на экран сумму чисел
my_sum_1(2, 3)

5


In [ ]:
# Результат работы функции 2
## Возвращает значение суммы, его можно сохранить в переменную
result = my_sum_2(2, 3)
print(result)

5


In [ ]:
# Результат работы функции 3
## Возвращает значение суммы, его можно сохранить в переменную
result = my_sum_3(2, 3)
print(result)

5


#### Так НЕ правильно

In [ ]:
def my_sum_4(a, b):
    return 
    c = a + b

In [ ]:
# ничего не возвращает (!!!)
my_sum_4(4, 5)

In [ ]:
def my_sum_5(a, b):
    c = a + b
    return print(c)

In [ ]:
# принтит, но ничего не возвращает (!!!)
result = my_sum_5(4, 5)

9


In [ ]:
print(result)

None


In [ ]:
# А это вообще не понятно что...
def sum_elements(a):
    return
    count = 0
    
    for i in range(len(a)):
        count+=a[i]
    
    

In [ ]:
result = sum_elements(3)
print(result)

None


##  2. Классы

Еще раз:

#### Так правильно

In [ ]:
class Circle:
    
    # конструктор класса
    def __init__(self, radius):
        self.radius = radius
    
    # метод для расчета диаметра
    def diameter(self):
        diam = self.radius * 2
        return diam
    
    # метод для расчета длины окружности
    def length(self):
        leng = 2 * 3.14 * self.radius
        return leng
    
    # метод для расчета площади
    def area(self):
        s = 3.14 * (self.radius ** 2)
        return s

In [ ]:
# Экземпляр класса номер 1
a = Circle(5)
a.area()

78.5

In [ ]:
# Экземпляр класса номер 2
b = Circle(1)
b.area()

3.14

## Библиотека NumPy

NumPy - векторные/научные вычисления. Пакет содержит функциональные средства для работы с многомерными массивами и высокоуровневыми математическими функциями

Импортирование библиотеки:

In [ ]:
import numpy as np

### 1. Структура np.ndarray

np.ndarray - это массив, содержащий элементы **одного типа**. 

Давайте посмотрим что это значит:

In [ ]:
a = [2, 4, 5]
a

[2, 4, 5]

In [ ]:
a_numpy = np.array(a)
a_numpy.dtype

dtype('int32')

In [ ]:
b = [2, 3.14]
np.array(b)

array([2.  , 3.14])

In [ ]:
c = [2, 3.14, 'kotiki']
np.array(c)

array(['2', '3.14', 'kotiki'], dtype='<U32')

In [ ]:
my_list = [2, 4.14, 'kotiki', [2,3,4]]
my_list

[2, 4.14, 'kotiki', [2, 3, 4]]

In [ ]:
# Вариант с object работает
np.array([2, 4.14, 'kotiki', [2, 4, 5]], dtype='object')

array([2, 4.14, 'kotiki', list([2, 4, 5])], dtype=object)

### 2. Типы данных

В NumPy реализованы свои типы данных, которые отличаются от встроенных в Python.

Например, нативный int ничем не ограничен (кроме вашей памяти). Целые числа в numpy имеют фиксированный размер, np.int8, np.int16...

Другое различие кроется во встроенных методах:

In [ ]:
a_python = 123
a_numpy = np.int32(123)

In [ ]:
a_python

123

In [ ]:
a_numpy

123

In [ ]:
# встроенный в python целочисленный тип
type(a_python)

int

In [ ]:
# встроенный в библиотеку numpy один из целочисленных типов
type(a_numpy)

numpy.int32

### 3. Одномерные и многомерные массивы

Одномерные numpy массивы

In [ ]:
# массив из целых чисел
a = np.array([1, 2, 3, 4, 5])

In [ ]:
# массив из строк
b = np.array(['cat', 'mouse', 'dog', 'rat'])

In [ ]:
a.dtype

dtype('int32')

In [ ]:
b.dtype

dtype('<U5')

In [ ]:
# проверяем размерность
## размерность массива
a.shape

(5,)

In [ ]:
# кол-во элементов в массиве
a.size

5

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
# изменение размерности массива
a.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Индексация

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a[0]

1

In [ ]:
a[1]

2

In [ ]:
a[-1]

6

In [ ]:
a[:-2]

array([1, 2, 3, 4])

In [ ]:
a[1:4]

array([2, 3, 4])

In [ ]:
# подвыборка массива с логическими условиями
a[(a > 4) & (a < 6)]

array([5])

In [ ]:
a[a > 4]

array([5, 6])

#### Встроенные методы

чтобы увидеть все доступные методы, после точки нажмите "Tab"

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
# сумма всех элементов массива
a.sum()

21

In [ ]:
# среднее всех элементов массива
a.mean()

3.5

In [ ]:
# максимальный элемент массива
a.max()

6

In [ ]:
# минимальный элемент массива
a.min()

1

In [ ]:
# результат перемножения всех элементов массива
a.prod()

720

In [ ]:
# массив со строками
b

array(['cat', 'mouse', 'dog', 'rat'], dtype='<U5')

In [ ]:
# сортировка
b.sort()
b

array(['cat', 'dog', 'mouse', 'rat'], dtype='<U5')

In [ ]:
%%timeit
a.sum()

2.21 µs ± 228 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%%timeit
a.mean()

5.08 µs ± 35.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
# меряет время выполнения всей ячейки

In [ ]:
%%timeit
a.sum()
a.mean()

7.15 µs ± 64.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
# Задаем параметры 
## n - кол-во циклов повторений
## m - кол-во повторений в одном цикле

In [ ]:
%%timeit -n 5 -r 10
a.sum()

The slowest run took 4.13 times longer than the fastest. This could mean that an intermediate result is being cached.
2.3 µs ± 1.59 µs per loop (mean ± std. dev. of 10 runs, 5 loops each)


#### Операции с массивами

In [ ]:
# np.arange - создает массив из чисел, идущих по порядку
## числа от 0 до 5 не включительно
print(np.arange(5))

[0 1 2 3 4]


In [ ]:
# числа от 3 до 6, 6 не включительно
print(np.arange(3, 6))

[3 4 5]


In [ ]:
# разница между числами = 5
print(np.arange(3, 16, 5))

[ 3  8 13]


In [ ]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [ ]:
b = np.arange(3, 8)
print(b)

[3 4 5 6 7]


In [ ]:
# сумма двух массивов
a + b

array([ 3,  5,  7,  9, 11])

In [ ]:
# разность двух массивов
a - b

array([-3, -3, -3, -3, -3])

In [ ]:
# деление
a / b

array([0.        , 0.25      , 0.4       , 0.5       , 0.57142857])

In [ ]:
# обратите внимание, что python нормально обработал деление на ноль
## inf - infinite value, бесконочность
b / a

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([ inf, 4.  , 2.5 , 2.  , 1.75])

In [ ]:
# поэлементное умножение двух массивов
a * b

array([ 0,  4, 10, 18, 28])

In [ ]:
# поэлементное возведение в степень
a ** b

array([    0,     1,    32,   729, 16384], dtype=int32)

In [ ]:
# поэлементное целочисленное деление
## обратите внимание на результат деления на ноль в этом случае
b // a

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([0, 4, 2, 2, 1], dtype=int32)

In [ ]:
# методы работают и без создания новой переменной, но нужны скобочки ()
(a * b - a).sum()

50

### Многомерные массивы

2D - матрица

3D, ..., nD - тензоры

In [ ]:
# создаем двумерный массив
a = np.array([[3, 6, 2, 7],
             [9, 2, 4, 8],
             [8, 2, 3, 6]])

print(a)

[[3 6 2 7]
 [9 2 4 8]
 [8 2 3 6]]


In [ ]:
# размерность массива
a.shape

(3, 4)

In [ ]:
# кол-во элементов массива
a.size

12

#### Индексация

построчно

In [ ]:
a_list = [[3, 6, 2, 7],
          [9, 2, 4, 8],
          [8, 2, 3, 6]]

a_list

[[3, 6, 2, 7], [9, 2, 4, 8], [8, 2, 3, 6]]

In [ ]:
# нулевая строка
a[0]

array([3, 6, 2, 7])

In [ ]:
# первая строка
a[1]

array([9, 2, 4, 8])

In [ ]:
# последняя строка
a[-1]

array([8, 2, 3, 6])

поэлементно

In [ ]:
a

array([[3, 6, 2, 7],
       [9, 2, 4, 8],
       [8, 2, 3, 6]])

In [ ]:
# элемент с индексом 0 по строке и 0 по столбцу
a[0,0]

3

In [ ]:
# элемент с индексом 0 по строке и 1 по столбцу
a[0,1]

6

In [ ]:
# элемент с индексом 1 по строке и 0 по столбцу
a[1,0]

9

по столбцам

In [ ]:
# нулевой столбец
a[:, 0]

array([3, 9, 8])

In [ ]:
# первый столбец
a[:, 1]

array([6, 2, 2])

#### Операции с двумерными массивами и встроенные методы

In [ ]:
print(a)

[[3 6 2 7]
 [9 2 4 8]
 [8 2 3 6]]


In [ ]:
# сумма двух элементов массива
a.sum()

60

In [ ]:
# сумма по столбцам
a.min(axis=0)

array([3, 2, 2, 6])

In [ ]:
# сумма по строкам
a.sum(axis=1)

array([18, 23, 19])

In [ ]:
# np.ones_like создает массив из единиц такой же размерности как и массив а
b = np.ones_like(a)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# np.zeros создает массив из нулей заданной размерности
a_ = np.zeros(5)
a_

array([0., 0., 0., 0., 0.])

In [ ]:
# умножение всех элементов массива на число
b = b * 2
print(b)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [ ]:
print(a)

[[3 6 2 7]
 [9 2 4 8]
 [8 2 3 6]]


In [ ]:
# поэлементное умножение двух массивов
a * b

array([[ 6, 12,  4, 14],
       [18,  4,  8, 16],
       [16,  4,  6, 12]])

#### структура np.matrix

In [ ]:
np.matrix(a)

matrix([[3, 6, 2, 7],
        [9, 2, 4, 8],
        [8, 2, 3, 6]])

In [ ]:
# в случае с np.matrix выполняется матричное умножение, а не поэлементное (!!!)
np.matrix(b) * np.matrix(a).T

matrix([[36, 46, 38],
        [36, 46, 38],
        [36, 46, 38]])

#### Тензоры a.k.a. многомерные массивы


In [ ]:
# создаем пятимерный массив из единиц размерности 2 на 3 на 4 на 6 на 5
c = np.ones((2, 3, 4, 6, 5))
print(c)

[[[[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]]


  [[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1

In [ ]:
# создаем трехмерный массив руками
d = np.array([[[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]],
             
              [[13, 14, 15, 16],
              [17, 18, 19, 20],
              [21, 22, 23, 24]]])

print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
# проверяем размерность
d.shape

(2, 3, 4)

Как поэлементно обращаться к тензорам?

In [ ]:
# элемент с индексами 0 по всем осям
d[0, 0, 0]

1

In [ ]:
# только первые строки
d[:,  0, :]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [ ]:
# только первые строки и только первые 2 элемента каждой строки
d[:,  0, :2]

array([[ 1,  2],
       [13, 14]])

In [ ]:
# сумма элементов по второй оси
d.sum(axis=2)

array([[10, 26, 42],
       [58, 74, 90]])

### Матричные операции

Транспонирование

метод .T

In [ ]:
print(a)

[[3 6 2 7]
 [9 2 4 8]
 [8 2 3 6]]


In [ ]:
aT = a.T
print(a.T)

[[3 9 8]
 [6 2 2]
 [2 4 3]
 [7 8 6]]


Умножение двух матриц

метод .dot

In [ ]:
print(a)

[[3 6 2 7]
 [9 2 4 8]
 [8 2 3 6]]


In [ ]:
print(b)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [ ]:
# это не умножение(!!!)
## это поэлементное умножение
a * b

array([[ 6, 12,  4, 14],
       [18,  4,  8, 16],
       [16,  4,  6, 12]])

In [ ]:
# вот это умножение:
## метод .dot
c = aT.dot(b)
print(c)

[[40 40 40 40]
 [20 20 20 20]
 [18 18 18 18]
 [42 42 42 42]]


In [ ]:
a.T.dot(b)

array([[40, 40, 40, 40],
       [20, 20, 20, 20],
       [18, 18, 18, 18],
       [42, 42, 42, 42]])

### Семплирование из распределений

Описание всех возможностей модуля np.random:

(это не то же самое, что модуль random из домашки (!!!))

https://www.numpy.org/devdocs/reference/routines.random.html


In [ ]:
# создаем массив размера 5 на 5 со случайными числами из стандартного нормального распределения
rr = np.random.normal(0, 1, (5,5))
print(rr)

[[ 0.92060194 -0.83539529  0.00522987 -0.65466365 -0.03294246]
 [ 0.48839054  0.49606078 -0.24934253  0.49055353 -0.81734676]
 [ 0.14592308  0.4749484  -1.36604051 -1.81759374 -0.17304801]
 [ 1.3622581  -0.14016167  0.09788168 -1.28576094 -0.75908084]
 [-0.57914482 -0.83367818 -0.97800993  0.46615984 -0.21306256]]


### Обратная матрица и модуль np.linalg

https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [ ]:
np.linalg.inv(rr)

array([[ 1.58180431,  1.0013669 ,  0.23978475, -1.00988076, -0.68283072],
       [-0.04320111,  0.50472672,  0.309373  , -0.44222664, -0.60528803],
       [-0.93237915, -0.74736612, -0.54310705,  0.96391993,  0.01812892],
       [ 0.66393822,  0.74031835, -0.08437603, -0.76629445, -0.14403294],
       [ 1.60187446,  0.35352094,  0.44608379, -1.62579978, -0.86734778]])

### Чтение файлов

In [ ]:
# грузим массив из файла .csv
my_data = np.loadtxt('iris.csv', delimiter=',')

In [ ]:
# вот что мы подгрузили
my_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
# массив имеет тип np.array сразу
type(my_data)

numpy.ndarray

In [ ]:
# тип подгруженных данных - float64
my_data.dtype

dtype('float64')